apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: modern-python-app-api
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: modern-python-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: adhol/modern-python-app:a0c8a4cddc8d56bdc4019dfe6afd5bf069047f8e
        name: modern-python-app
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: server
  name: modern-python-app-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: modern-python-app-api
            port:
              name: http
        path: /
        pathType: Prefix
