apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: modern-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: adhol/modern-python-app
          name: modern-python-app
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"