name: CI Workflow

on: [ push ]

# on:
#   push:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo code
      - uses: actions/checkout@v2
      
      # Setup your CI build environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      # Check for Linting errors
      - name: Lint with flake8 and black
        run: |
          black .
          flake8 .
      
      # Run a vulnerability scan on Project dependencies
      - name: Safety check
        run: |
          safety check
      # Run your unit test suite
      # - name: Test with pytest and coverage
      #   run: |
      #     coverage run -m pytest -v

      # Build and push your image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/modern-python-app
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    # Checkout code
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
       cd manifest
       kustomize edit set image adhol/modern-python-app=$DOCKER_USERNAME/modern-python-app:$GITHUB_SHA
       mkdir -p ../deployment
       kustomize build . > ../deployment/manifest.yaml
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker tag"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}